config/routes.rb
RailsBlog::Application.routes.draw do
  
  devise_for :users,
             :path => "",
             :path_names => { :sign_in => 'login', :sign_out => 'logout' },
             :skip => [:passwords, :registrations],
             :controllers => { :sessions => "admin/sessions" }

  root :to => 'home#index'
  get 'install' => 'home#install'
  post 'installing' => 'home#installing'

  namespace :admin do
    root :to => 'home#index'
    resources :categories do
      post 'search', :on => :collection
      post 'destroy_multiple', :on => :collection
      get 'page/:page', :action => :index, :on => :collection
    end
    resources :logs, :only => [:index] do
      get 'categories', :on => :collection
      get 'albums',     :on => :collection
      get 'photos',     :on => :collection
      get 'blogs',      :on => :collection
    end
    resources :albums do
      get 'delete', :on => :member
      resources :photos, :only => [:index, :new, :create, :destroy] do
        post 'destroy_multiple', :on => :collection
        get 'galleries', :on => :collection
      end
    end
    resources :photos, :only => [:index, :new, :create, :destroy]
    resources :blogs do
      post 'search', :on => :collection
      post 'destroy_multiple', :on => :collection
      get 'page/:page', :action => :index, :on => :collection
    end
    resources :editor_photos
  end

end

app/models/album.rb
class Album < ActiveRecord::Base
  attr_accessible :name, :description, :permission_cd, :password

  # Associations
  has_many :logs, :as => :recordable, :order => "created_at DESC"
  has_many :photos

  # enums
  as_enum :permission, { :public => 0, :private => 1, :password => 2 }

  # Validates
  validates :name, :permission_cd, :presence => true
	with_options :if => :name? do |name|
    name.validates :name, :length => { :within => 2..30 }
    name.validates :name, :uniqueness => true
  end
  with_options :if => :permission_cd? do |permission_cd|
  	permission_cd.validates :permission_cd, :numericality => { :only_integer => true }
  end

  # scopes
  scope :created_desc, order("created_at DESC")

  # Callbacks
  before_save :create_or_update_log
  before_destroy :destroy_log

  # Methods
  def self.logs(action = nil, limit = nil)
    result = Log.with_model(self.model_name).created_desc
    if action != :all || action.blank?
      result = result.with_action(action)
    end
    if !limit.blank?
      result = result.limit(limit)
    end
    result
  end

  def create_or_update_log
    action = self.new_record? ? "create" : "update"
    self.logs.build(:action => action, :message => self.name)
  end

  def destroy_log
    self.logs.create(:action => "destroy", :message => self.name)
  end

end

app/controllers/admin/albums_controller.rb
class Admin::AlbumsController < Admin::ApplicationController
	
	def index
		@albums = Album.page(params[:page]).per(Setting.admin_AlbumPageSize).created_desc
	end

	def new
		@album = Album.new
		@remote = params[:remote].blank? ? true : false
	end

	def create
		@album = Album.new params[:album]
		if @album.save
			respond_to do |format|
				format.html { redirect_to admin_album_photos_url(@album), 
									:notice => t("helpers.messages.new", :model_name => Album.model_name.human) }
				format.js
			end
		end
	end

	def edit
		@album = Album.find params[:id]
	end

	def update
		@album = Album.find params[:id]
    if @album.update_attributes params[:album]
      flash[:notice] = t("helpers.messages.edit", :model_name => Album.model_name.human)
    end
	end

	def delete
		@album = Album.find params[:id]
	end

	def destroy
		@album = Album.find params[:id]
		if !params[:delete_all].blank?
			@album.photos.destroy
		end
		if @album.destroy
			redirect_to :admin_albums, :notice => t("helpers.messages.destroy", :model_name => Album.model_name.human)
		else
			redirect_to :admin_albums, :alert => t("helpers.messages.error")
		end
	end
	
end

app/helpers/admin/albums_helper.rb
module Admin::AlbumsHelper
end

app/views/admin/albums/_album.html.erb
<li class="span3 album_<%= album.id %>">
	<a href="<%= admin_album_photos_path(album) %>" class="thumbnail" rel="popover" data-content="<%= "<h4>#{album.name}</h4><p class='description'>#{album.description}</p>" %>">
		<%= image_tag "admin/default-album.png" %>
	</a>
	<span class="name"><%= album.name %></span>
	<div class="other">
		<a href="<%= edit_admin_album_path(album) %>" data-remote="true" rel="tooltip" title="<%= t("helpers.links.edit", :model_name => Album.model_name.human) %>" data-toggle="modal" data-target="#ajax-form">
			<i class="icon-edit icon-large"></i>
		</a>
		<a href="<%= delete_admin_album_path(album) %>" data-remote="true" data-toggle="modal" data-target="#ajax-form" rel="tooltip" title="<%= t("helpers.links.destroy", :model_name => Album.model_name.human) %>">
			<i class="icon-trash icon-large"></i>
		</a>
		<% if !album.public? %>
			<span class="permission" rel="tooltip" title="<%= album.human_permission %>">
				<%= raw "<i class=\"icon-key icon-large\"></i>" if album.password? %>
				<%= raw "<i class=\"icon-lock icon-large\"></i>" if album.private? %>
			</span>
		<% end -%>
		<span class="count badge pull-right" rel="tooltip" title="<%= t("helpers.messages.album.photo_count", :count => album.photos_count) %>"><%= album.photos_count %></span>
	</div>
</li>

app/views/admin/albums/_base.html.erb
<%- model_class = Album -%>
<%= content_for :title do -%>
	<% if %w(index).include?(action_name) -%>
		<%= t("helpers.links.list", :model_name => model_class.model_name.human) %>
	<% end -%>

	<% if %w(new create).include?(action_name) -%>
		<%= t("helpers.links.new", :model_name => model_class.model_name.human) %>
	<% end -%>

	<% if %w(edit update).include?(action_name) -%>
		<%= t("helpers.links.edit", :model_name => model_class.model_name.human) %>
	<% end -%>

	<% if %w(search).include?(action_name) -%>
		<%= t("helpers.links.search", :model_name => model_class.model_name.human) %>
	<% end -%>
<% end -%>

<%= content_for :sitemaps do -%>
	<a href="<%= admin_albums_path %>"><%= model_class.model_name.human %></a>
	<span class="divider">/</span>
	<% if %w(index).include?(action_name) -%>
		<span class="active"><%= t("helpers.links.list", :model_name => model_class.model_name.human) %></span>
	<% end -%>

	<% if %w(new create).include?(action_name) -%>
		<span class="active"><%= t("helpers.links.new", :model_name => model_class.model_name.human) %></span>
	<% end -%>

	<% if %w(edit update).include?(action_name) -%>
		<span class="active"><%= t("helpers.links.edit", :model_name => model_class.model_name.human) %></span>
	<% end -%>

	<% if %w(search).include?(action_name) -%>
		<span class="active"><%= t("helpers.links.search", :model_name => model_class.model_name.human) %></span>
	<% end -%>
<% end -%>

<% if %w(index).include?(action_name) -%>
	<div id="toolbar">
		<div class="btn-group">
			<a href="<%= new_admin_album_path(:remote => false) %>" class="btn" data-toggle="modal" data-target="#ajax-form" data-remote="true">
				<i class="icon-folder-open icon-large"></i>
				<b><%= t("helpers.links.new", :model_name => model_class.model_name.human) %></b>
			</a>
			<a href="<%= new_admin_photo_path %>" class="btn">
				<i class="icon-picture icon-large"></i>
				<b><%= t("helpers.links.new", :model_name => Photo.model_name.human) %></b>
			</a>
		</div>
	</div>
<% end -%>

app/views/admin/albums/_destroy_form.html.erb
<%- model_class = Album -%>
<%= simple_form_for [:admin, @album], :html => { :class => "form-horizontal", :id => :deleteAlbum }, :method => :delete do |f| %>
<div class="modal-header">
  <a class="close" data-dismiss="modal">×</a>
  <h3><%= t("helpers.links.destroy", :model_name => model_class.model_name.human) %></h3>
</div>
<div class="modal-body">
  <h4>你确定要删除该相册吗？</h4>
  <div class="control-group">
    <div class="controls">
      <label class="checkbox">
        <input type="checkbox" id="deleteAll" value="1" name="delete_all" />
        删除该相册下全部照片？
      </label>
    </div>
  </div>
  <div class="alert">
    <h4>注意：</h4>
    默认情况下如果删除了相册，会将该相册下所有照片移动到<strong>默认相册</strong>内！
  </div>
</div>
<div class="modal-footer">
	<button type="submit" class="btn btn-primary">
  	<i class="icon-pencil icon-large"></i>
    <b><%= t("helpers.links.destroy", :model_name => model_class.model_name.human) %></b>
  </button>
  <a href="#" class="btn" data-dismiss="modal"><%= t("helpers.links.close") %></a>
</div>
<% end -%>

app/views/admin/albums/_form.html.erb
<%- model_class = Album -%>
<%= simple_form_for [:admin, @album], :html => { :class => "form-horizontal" }, :remote => @remote do |f| %>
<div class="modal-header">
  <a class="close" data-dismiss="modal">×</a>
  <h3><%= t("helpers.links.#{@album.new_record? ? "new" : "edit"}", :model_name => model_class.model_name.human) %></h3>
</div>
<div class="modal-body">
	<%= error_messages_for @album, :class => "control-group alert alert-error fade in", :close => :true %>
  <%= f.input :name, :input_html => { :class => :span4 } %>
  <%= f.input :description, :as => :text, :input_html => { :class => :span4 } %>
  <%= f.input :permission_cd do %>
  	<%= f.select :permission_cd, model_class.permissions_for_select(:value) %>
  <% end -%>
  <%= f.input :password, :input_html => { :class => :span4 } %>
</div>
<div class="modal-footer">
	<button type="submit" class="btn btn-primary">
  	<i class="icon-pencil icon-large"></i>
  	<% if @album.new_record? %>
    	<b><%= t("helpers.links.new", :model_name => model_class.model_name.human) %></b>
  	<% else -%>
  		<b><%= t("helpers.links.edit", :model_name => model_class.model_name.human) %></b>
  	<% end -%>
  </button>
  <a href="#" class="btn" data-dismiss="modal"><%= t("helpers.links.close") %></a>
</div>
<% end -%>

app/views/admin/albums/create.js.erb
<% if @album.errors.any? -%>
	$("#ajax-form .modal-body")
		.find("#errorExplanation").remove()
		.end()
		.prepend("<%= j(error_messages_for(@album, :class => 'control-group alert alert-error fade in', :close => :true)) %>")
<% else -%>
	$(".modal")
		.find(":input:not(input[type=submit])").val("")
		.end()
		.modal('hide');
		
	$("select#photo_album_id").prepend("<%= j(content_tag(:option, @album.name, :value => @album.id, :selected => true)) %>");
<% end -%>

app/views/admin/albums/delete.js.erb
$("#ajax-form.modal > form").replaceWith('<%= j(render("destroy_form")) %>');

app/views/admin/albums/edit.js.erb
$("#ajax-form.modal > form").replaceWith('<%= j(render("form")) %>');

app/views/admin/albums/index.html.erb
<%= render "base" %>
<div id="albums">
	<div class="row">
		<div class="span12">
			<ul class="thumbnails">
				<% @albums.each do |album| -%>
				<%= render :partial => album %>
				<% end -%>
			</ul>
		</div>
	</div>
</div>
<div id="ajax-form" class="modal hide fade in">
	<form></form>
</div>
<div class="table-footer clearfix">
  <div class="paginates-info"><%= page_entries_info @albums %></div>
  <%= paginate @albums, :theme => "admin" %>
</div>

app/views/admin/albums/new.js.erb
$("#ajax-form.modal > form").replaceWith('<%= j(render("form")) %>');

app/views/admin/albums/update.js.erb
<% if @album.errors.any? -%>
	$("#ajax-form .modal-body")
		.find("#errorExplanation").remove()
		.end()
		.prepend("<%= j(error_messages_for(@album, :class => 'control-group alert alert-error fade in', :close => :true)) %>")
<% else -%>
	$(".modal")
		.find(":input:not(input[type=submit])").val("")
		.end()
		.modal('hide');
		
	$("#main div.well:first")
		.find(".alert").remove()
		.end().
		prepend("<%= j(bootstrap_flash) %>");

	$("#albums .thumbnails li.album_<%= @album.id %>").replaceWith("<%= j(render(:partial => @album)) %>");	
<% end -%>