config/routes.rb
RailsBlog::Application.routes.draw do
  
  devise_for :users,
             :path => "",
             :path_names => { :sign_in => 'login', :sign_out => 'logout' },
             :skip => [:passwords, :registrations],
             :controllers => { :sessions => "admin/sessions" }

  root :to => 'home#index'
  get 'install' => 'home#install'
  post 'installing' => 'home#installing'

  namespace :admin do
    root :to => 'home#index'
    resources :categories do
      post 'search', :on => :collection
      post 'destroy_multiple', :on => :collection
      get 'page/:page', :action => :index, :on => :collection
    end
    resources :logs, :only => [:index] do
      get 'categories', :on => :collection
      get 'albums',     :on => :collection
      get 'photos',     :on => :collection
      get 'blogs',      :on => :collection
    end
    resources :albums do
      get 'delete', :on => :member
      resources :photos, :only => [:index, :new, :create, :destroy] do
        post 'destroy_multiple', :on => :collection
        get 'galleries', :on => :collection
      end
    end
    resources :photos, :only => [:index, :new, :create, :destroy]
    resources :blogs do
      post 'search', :on => :collection
      post 'destroy_multiple', :on => :collection
      get 'page/:page', :action => :index, :on => :collection
    end
    resources :editor_photos
  end

end

app/models/album.rb
class Album < ActiveRecord::Base
  attr_accessible :name, :description, :permission_cd, :password

  # Associations
  has_many :logs, :as => :recordable, :order => "created_at DESC"
  has_many :photos

  # enums
  as_enum :permission, { :public => 0, :private => 1, :password => 2 }

  # Validates
  validates :name, :permission_cd, :presence => true
	with_options :if => :name? do |name|
    name.validates :name, :length => { :within => 2..30 }
    name.validates :name, :uniqueness => true
  end
  with_options :if => :permission_cd? do |permission_cd|
  	permission_cd.validates :permission_cd, :numericality => { :only_integer => true }
  end

  # scopes
  scope :created_desc, order("created_at DESC")

  # Callbacks
  before_save :create_or_update_log
  before_destroy :destroy_log

  # Methods
  def self.logs(action = nil, limit = nil)
    result = Log.with_model(self.model_name).created_desc
    if action != :all || action.blank?
      result = result.with_action(action)
    end
    if !limit.blank?
      result = result.limit(limit)
    end
    result
  end

  def create_or_update_log
    action = self.new_record? ? "create" : "update"
    self.logs.build(:action => action, :message => self.name)
  end

  def destroy_log
    self.logs.create(:action => "destroy", :message => self.name)
  end

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  include Rails.application.routes.url_helpers
  attr_accessible :name, :description, :image, :album_id

  # Associations
  has_many :logs, :as => :recordable, :order => "created_at DESC"
  belongs_to :album, :counter_cache => true

  # Callbacks
  before_save :update_image_attributes, :create_or_update_log
  before_destroy :destroy_log

  # carrierwave
  mount_uploader :image, ImageUploader

  # Validates
  validates :album_id, :image, :presence => true
  with_options :if => :name? do |name|
    name.validates :name, :length => { :within => 2..30 }
  end

  # scopes
  scope :created_desc, order("created_at DESC")

  # Methods
  def self.logs(action = nil, limit = nil)
    result = Log.with_model(self.model_name).created_desc
    if action != :all || action.blank?
      result = result.with_action(action)
    end
    if !limit.blank?
      result = result.limit(limit)
    end
    result
  end

  def update_image_attributes
    if image.present? && image_changed?
      self.name = image.file.basename
      self.image_size = image.file.size
      self.image_content_type = image.file.content_type
    end
  end

  def create_or_update_log
    action = self.new_record? ? "create" : "update"
    self.logs.build(:action => action, :message => self.name)
  end

  def destroy_log
    self.logs.create(:action => "destroy", :message => self.name)
  end

  def to_jq_upload
    {
      "id" => read_attribute(:id),
      "name" => read_attribute(:name),
      "size" => image.size,
      "url" => image.url,
      "thumbnail_url" => image.thumb.url,
      "delete_url" => admin_photo_path(:id => id),
      "delete_type" => "DELETE" 
    }
  end

end

app/controllers/admin/photos_controller.rb
class Admin::PhotosController < Admin::ApplicationController

	before_filter :fill_album

	def index
		if @album.blank?
			@photos = Photo.page(params[:page]).per(Setting.admin_PhotoPageSize).created_desc
		else
			@photos = Photo.page(params[:page])
										 .per(Setting.admin_PhotoPageSize)
										 .created_desc
										 .where(:album_id => @album.id)
		end
	end

	def new
		@photo = Photo.new
	end

	def create
		@photo = Photo.new params[:photo]
		if @photo.save
			respond_to do |format|
				format.html {
					render :json => [@photo.to_jq_upload].to_json,
								 :content_type => "text/html",
								 :layout => :false
				}
				format.json {
					render :json => [@photo.to_jq_upload].to_json
				}
			end
		else
			render :json => [{ :error => "emptyAlbum" }]
		end
	end

	def destroy
		@photo = Photo.find params[:id]
		@photo.destroy
		respond_to do |format|
			format.html { redirect_to admin_album_photos_url(@album), 
									:notice => t("helpers.messages.destroy", :model_name => Photo.model_name.human) }
			format.json { render :json => true }
		end
	end

	def destroy_multiple
		if params[:photo_ids].blank?
			return redirect_to admin_album_photos_url(@album),
												 :alert => t("helpers.messages.selected_error",
												 :model_name => Photo.model_name.human)
		end
		if Photo.destroy(params[:photo_ids])
			redirect_to admin_album_photos_url(@album), 
									:notice => t("helpers.messages.destroy_multiple", 
									:count => params[:photo_ids].size,
									:model_name => Photo.model_name.human)
		else
			redirect_to admin_album_photos_url(@album), :alert => t("helpers.messages.notices.error")
		end
	end

	def galleries
		@photos = @album.photos.created_desc
	end

	protected
	def fill_album
		@album = Album.find(params[:album_id]) if !params[:album_id].blank?
	end
	
end

app/helpers/admin/photos_helper.rb
module Admin::PhotosHelper
end

app/views/admin/photos/_base.html.erb
<%- model_class = Photo -%>
<%= content_for :title do -%>
	<% if %w(index galleries).include?(action_name) -%>
		<%= t("helpers.links.list", :model_name => model_class.model_name.human) %>
	<% end -%>

	<% if %w(new create).include?(action_name) -%>
		<%= t("helpers.links.new", :model_name => model_class.model_name.human) %>
	<% end -%>

	<% if %w(edit update).include?(action_name) -%>
		<%= t("helpers.links.edit", :model_name => model_class.model_name.human) %>
	<% end -%>

	<% if %w(search).include?(action_name) -%>
		<%= t("helpers.links.search", :model_name => model_class.model_name.human) %>
	<% end -%>
<% end -%>

<%= content_for :sitemaps do -%>
	<a href="<%= admin_albums_path %>"><%= Album.model_name.human %></a>
	<span class="divider">/</span>
	<% if %w(index galleries).include?(action_name) -%>
		<span class="active"><%= @album.name %></span>
	<% end -%>

	<% if %w(new create).include?(action_name) -%>
		<% if !@album.blank? %>
			<a href="<%= admin_album_photos_path(@album) %>"><%= @album.name %></a>
			<span class="divider">/</span>
		<% end -%>
		<span class="active"><%= t("helpers.links.new", :model_name => model_class.model_name.human) %></span>
	<% end -%>

	<% if %w(edit update).include?(action_name) -%>
		<span class="active"><%= t("helpers.links.edit", :model_name => model_class.model_name.human) %></span>
	<% end -%>

	<% if %w(search).include?(action_name) -%>
		<span class="active"><%= t("helpers.links.search", :model_name => model_class.model_name.human) %></span>
	<% end -%>
<% end -%>

<%= content_for :sidebar do -%>
	<% if %w(index).include?(action_name) -%>
		<div class="well sidebar-tip">
			<div class="page-header"><h5 class="info">小贴士</h5></div>
			<ul>
				<li>点击图片能选中图片，选中的图片边框呈现红色。</li>
				<li>鼠标移动到图片会显示删除等功能键。</li>
			</ul>
		</div>
		<div class="well sidebar-nav">
		  <%= log_tags(Photo.logs(:all, 20), :date_tag => false, :model_tag => false, :truncate => 19) %>
		</div>
	<% end -%>
	<% if %w(galleries).include?(action_name) -%>
		<div class="well sidebar-tip">
			<div class="page-header"><h5 class="info">小贴士</h5></div>
			<ul>
				<li>点击大图左右可浏览下一张。</li>
				<li>键盘左右键可浏览。</li>
			</ul>
		</div>
	<% end -%>
	<% if %w(new create).include?(action_name) -%>
		<div class="well sidebar-tip">
			<div class="page-header"><h5 class="info">小贴士</h5></div>
			<ul>
				<li>一次最多只能上传 <span class="badge badge-warning">50</span> 个文件。</li>
				<li>只能上传<strong>(JPG, GIF, PNG)</strong>的图片。</li>
				<li>每个文件小于10M。</li>
			</ul>
		</div>
		<div class="well sidebar-nav">
			<%= log_tags(Photo.logs(:all, 20), :date_tag => false, :model_tag => false, :truncate => 19) %>
		</div>
	<% end -%>
<% end -%>

<% if %w(index galleries).include?(action_name) -%>
	<div id="toolbar" class="clearfix">
		<% if %w(index).include?(action_name) %>
			<div class="btn-group pull-left">
				<a href="<%= new_admin_album_photo_path(@album) %>" class="btn">
					<i class="icon-picture icon-large"></i>
					<b><%= t("helpers.links.new", :model_name => model_class.model_name.human) %></b>
				</a>
				<a href="javascript:void(0);" class="btn delete-photos">
					<i class="icon-trash icon-large"></i>
					<b><%= t("helpers.links.delete_all") %></b>
				</a>
			</div>
		<% end -%>
			<div class="btn-group pull-right">
				<a href="<%= admin_album_photos_path(@album) %>" class="btn<%= " active" if action_name == "index" %>">
					<i class="icon-th icon-large"></i>
					<b><%= t("helpers.links.list_mode") %></b>
				</a>
				<a href="<%= galleries_admin_album_photos_path(@album) %>" class="btn delete-photos<%= " active" if action_name == "galleries" %>">
					<i class="icon-eye-open icon-large"></i>
					<b><%= t("helpers.links.gallery_mode") %></b>
				</a>
			</div>
	</div>
<% end -%>

app/views/admin/photos/_form.html.erb
<%= simple_form_for [:admin, @photo], :html => { :multipart => true, :id => "photos-fileupload", :class => "form-horizontal"  } do |f| %>
  <div class="row fileupload-buttonbar">
    <div class="span7">
      <span class="btn btn-success fileinput-button">
        <i class="icon-plus icon-white icon-large"></i>
        <b><%= t("fileupload.links.add") %></b>
        <input id="photo_image" multiple="multiple" name="photo[image]" type="file" />
      </span>
      <button type="submit" class="btn btn-primary start">
        <i class="icon-upload icon-white icon-large"></i>
        <b><%= t("fileupload.links.start_all") %></b>
      </button>
      <button type="reset" class="btn btn-warning cancel">
          <i class="icon-ban-circle icon-white icon-large"></i>
          <b><%= t("fileupload.links.cancel_all") %></b>
      </button>
      <button type="button" class="btn btn-danger delete">
          <i class="icon-trash icon-white icon-large"></i>
          <b><%= t("fileupload.links.delete") %></b>
      </button>
    </div>
    <div class="span5 fileupload-progress fade">
      <div class="progress progress-success progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
        <div class="bar" style="width:0%;"></div>
      </div>
    </div>
  </div>
  <div class="fileupload-loading"></div>
  <div class="control-group select required">
    <%= f.label :album_id %>
    <div class="controls">
      <% if @album.blank? %>
        <%= f.select :album_id, Album.created_desc.map { |a| [a.name, a.id] } %>
      <% else -%>
        <%= f.select :album_id, Album.created_desc.map { |a| [a.name, a.id] }, :selected => @album.id %>
      <% end -%>
      <span class="line">或</span>
      <a href="<%= new_admin_album_path %>" data-toggle="modal" data-target="#ajax-form" data-remote="true">
        <%= t("helpers.links.new", :model_name => Album.model_name.human) %>
      </a>
    </div>
  </div>
  <div id="photos-files">
    <ul class="files thumbnails"></ul>
  </div>
<% end %>
<div id="ajax-form" class="modal hide fade in">
  <form></form>
</div>

<%= render "template-upload" %>
<%= render "template-download" %>

app/views/admin/photos/_photo.html.erb
<li class="box template-download">
  <div class="image-box">
    <div class="preview">
        <%= image_tag photo.image.thumb %>
    </div>
    <div class="action delete hide">
      <a class="danger" href="<%= admin_album_photo_path(@album, photo) %>" data-method="delete">
        <i class="icon-trash icon-white icon-large"></i>
      </a>
    </div>
  </div>
  <span class="name"><%= photo.name %></span>
  <input id="<%= "photo_#{photo.id}" %>" name="photo_ids[]" type="checkbox" value="<%= photo.id %>" class="delete" />
</li>

app/views/admin/photos/_template-download.html.erb
<script id="template-download" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
  <li class="box template-download fade">
    <div href="javascript:void(0);" class="image-box">
      <div class="preview">
        {% if (file.thumbnail_url) { %}
          <img src="{%=file.thumbnail_url%}">
        {% } %}
        {% if (file.url) { %}
          <input id="photo_" name="photo" type="hidden" value="{%=file.url%}" />
        {% } %}
      </div>
      <span class="size">{%=o.formatFileSize(file.size)%}</span>
      <div class="action delete hide">
        <button class="danger" data-type="{%=file.delete_type%}" data-url="{%=file.delete_url%}">
          <i class="icon-trash icon-white icon-large"></i>
        </button>
      </div>
      {% if (file.error) { %}
        <div class="error">
          <span class="label label-important">
            {%=locale.fileupload.errors[file.error] || file.error%}
          </span>
        </div>
      {% } else { %}
        <div class="success">
          <i class="icon-ok"></i>
        </div>
      {% } %}
    </div>
    <span class="name">{%=file.name%}</span>
    <input type="checkbox" name="delete" value="1">
  </li>
{% } %}
</script>

app/views/admin/photos/_template-upload.html.erb
<script id="template-upload" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
  <li class="box template-upload fade">
    <a href="javascript:void(0);" class="image-box">
      <div class="preview"><span class="fade"></span></div>
      <span class="size">{%=o.formatFileSize(file.size)%}</span>
      <div class="action cancel hide">
        {% if (!i) { %}
          <button class="warning"><i class="icon-ban-circle icon-white icon-large"></i></button>
        {% } %}
      </div>
      {% if (file.error) { %}
        <div class="error">
          <span class="label label-important">
            {%=locale.fileupload.errors[file.error] || file.error%}
          </span>
        </div>
      {% } else if (o.files.valid && !i) { %}
        <div class="progress progress-success progress-striped active fade">
          <div class="bar" style="width:0%;"></div>
        </div>
        <div class="start">
          {% if (!o.options.autoUpload) { %}
            <button class="btn btn-primary">
              <i class="icon-upload icon-white icon-large"></i>
            </button>
          {% } %}
        </div>
      {% } else { %}
      {% } %}
    </a>
    <span class="name">{%=file.name%}</span>
  </li>
{% } %}
</script>

app/views/admin/photos/galleries.html.erb
<%= render "base" %>
<% if !@photos.blank? %>
<div id="gallery" class="ad-gallery">
  <div class="ad-nav">
    <div class="ad-thumbs">
      <ul class="ad-thumb-list">
      	<% @photos.each do |photo| -%>
      	<li>
      		<a href="<%= photo.image.url %>">
      			<%= image_tag photo.image.thumb_small, :class => "photo-#{photo.id}", 
      										:title => photo.name,
      										:alt => photo.description %>
      		</a>
      	</li>
      	<% end -%>
      </ul>
    </div>
  </div>
  <div class="image-wrapper">
  	<div class="ad-image-wrapper"></div>
  </div>
</div>
<% else -%>
<div class="alert alert-info">
  <span class="label label-info"><%= t("helpers.page_entries_info.one_page.display_entries.zero") %></span>
  <a href="<%= new_admin_album_photo_path(@album) %>" class="btn btn-info"><%= t("helpers.links.new", :model_name => Photo.model_name.human) %></a>
</div>
<div class="paginates-info">
	
</div>
<% end -%>

app/views/admin/photos/index.html.erb
<%= render "base" %>
<div id="photos-files">
	<%= simple_form_for :photos, :url => destroy_multiple_admin_album_photos_path(@album), 
											:html => { :id => :photos } do |f| -%>
	<ul class="files thumbnails">
		<% @photos.each do |photo| -%>
			<%= render :partial => photo %>
		<% end -%>
	</ul>
	<% end -%>
</div>
<div class="table-footer clearfix">
  <div class="paginates-info"><%= page_entries_info @photos %></div>
  <%= paginate @photos, :theme => "admin" %>
</div>

app/views/admin/photos/new.html.erb
<%= render "base" %>
<%= render "form" %>
<div id="upload-success" class="modal hide fade in">
	<div class="modal-header">
	  <a class="close" data-dismiss="modal">×</a>
	  <h3>上传完毕</h3>
	</div>
	<div class="modal-body">
	  <h4>你已经上传完毕。</h4>
	</div>
	<div class="modal-footer">
		<% if !@album.blank? %>
		  <a href="<%= admin_album_photos_path(@album) %>" class="btn btn-success"><%= t("helpers.links.back_album") %></a>
	  <% else -%>
		  <a href="<%= admin_albums_path %>" class="btn btn-success"><%= t("helpers.links.back_album") %></a>
	  <% end -%>
	  <a href="javascript:void(0);" class="btn btn-primary" data-dismiss="modal"><%= t("helpers.links.continue") %></a>
	</div>
</div>