config/routes.rb
RailsBlog::Application.routes.draw do
  
  devise_for :users,
             :path => "",
             :path_names => { :sign_in => 'login', :sign_out => 'logout' },
             :skip => [:passwords, :registrations],
             :controllers => { :sessions => "admin/sessions" }

  root :to => 'home#index'
  get 'install' => 'home#install'
  post 'installing' => 'home#installing'

  namespace :admin do
    root :to => 'home#index'
    resources :categories do
      post 'search', :on => :collection
      post 'destroy_multiple', :on => :collection
      get 'page/:page', :action => :index, :on => :collection
    end
    resources :logs, :only => [:index] do
      get 'categories', :on => :collection
      get 'albums',     :on => :collection
      get 'photos',     :on => :collection
      get 'blogs',      :on => :collection
    end
    resources :albums do
      get 'delete', :on => :member
      resources :photos, :only => [:index, :new, :create, :destroy] do
        post 'destroy_multiple', :on => :collection
        get 'galleries', :on => :collection
      end
    end
    resources :photos, :only => [:index, :new, :create, :destroy]
    resources :blogs do
      post 'search', :on => :collection
      post 'destroy_multiple', :on => :collection
      get 'page/:page', :action => :index, :on => :collection
    end
    resources :editor_photos
  end

end

app/models/log.rb
class Log < ActiveRecord::Base
	attr_accessible :action, :message

  belongs_to :recordable, :polymorphic => true

  # scopes
  scope :with_model, lambda { |model| where(:recordable_type => model) }
  scope :with_action, lambda { |action| where(:action => action) }
  scope :created_desc, order("created_at DESC")

end

app/controllers/admin/logs_controller.rb
class Admin::LogsController < Admin::ApplicationController

	def index
		@logs = Log.created_desc.page(params[:page]).per(Setting.admin_PageSize)
	end

	def categories
		@logs = Log.with_model(:Category).created_desc.page(params[:page]).per(Setting.admin_PageSize)
		render :index
	end

	def blogs
		@logs = Log.with_model(:Blog).created_desc.page(params[:page]).per(Setting.admin_PageSize)
		render :index
	end

	def albums
		@logs = Log.with_model(:Album).created_desc.page(params[:page]).per(Setting.admin_PageSize)
		render :index
	end

	def photos
		@logs = Log.with_model(:Photo).created_desc.page(params[:page]).per(Setting.admin_PageSize)
		render :index
	end

end

app/views/admin/logs/_base.html.erb
<%- model_class = Log -%>
<%= content_for :title do -%>
	<% if %w(index).include?(action_name) -%>
		<%= "#{t("helpers.links.all")}#{t("helpers.links.log")}" %>
	<% end -%>
	<% if %w(categories).include?(action_name) -%>
		<%= "#{Category.model_name.human}#{t("helpers.links.log")}" %>
	<% end -%>
	<% if %w(blogs).include?(action_name) -%>
		<%= "#{Blog.model_name.human}#{t("helpers.links.log")}" %>
	<% end -%>
	<% if %w(albums).include?(action_name) -%>
		<%= "#{Album.model_name.human}#{t("helpers.links.log")}" %>
	<% end -%>
	<% if %w(photos).include?(action_name) -%>
		<%= "#{Photo.model_name.human}#{t("helpers.links.log")}" %>
	<% end -%>
<% end -%>

<%= content_for :sitemaps do -%>
	<a href="<%= admin_logs_path %>"><%= model_class.model_name.human %></a>
	<span class="divider">/</span>
	<% if %w(index).include?(action_name) -%>
		<span class="active"><%= "#{t("helpers.links.all")}#{t("helpers.links.log")}" %></span>
	<% end -%>
	<% if %w(categories).include?(action_name) -%>
		<span class="active"><%= "#{Category.model_name.human}#{t("helpers.links.log")}" %></span>
	<% end -%>
	<% if %w(blogs).include?(action_name) -%>
		<span class="active"><%= "#{Blog.model_name.human}#{t("helpers.links.log")}" %></span>
	<% end -%>
	<% if %w(albums).include?(action_name) -%>
		<span class="active"><%= "#{Album.model_name.human}#{t("helpers.links.log")}" %></span>
	<% end -%>
	<% if %w(photos).include?(action_name) -%>
		<span class="active"><%= "#{Photo.model_name.human}#{t("helpers.links.log")}" %></span>
	<% end -%>
<% end -%>

app/views/admin/logs/_tabs.html.erb
<ul class="nav nav-tabs">
	<li<%= " class=active" if %w(index).include?(action_name) %>>
		<a href="<%= admin_logs_path %>" title="<%= t("helpers.links.all") %>"><%= t("helpers.links.all") %></a>
	</li>
	<li<%= " class=active" if %w(categories).include?(action_name) %>>
		<a href="<%= categories_admin_logs_path %>" title="<%= Category.model_name.human %>"><%= Category.model_name.human %></a>
	</li>
	<li<%= " class=active" if %w(blogs).include?(action_name) %>>
		<a href="<%= blogs_admin_logs_path %>" title="<%= Blog.model_name.human %>"><%= Blog.model_name.human %></a>
	</li>
	<li<%= " class=active" if %w(albums).include?(action_name) %>>
		<a href="<%= albums_admin_logs_path %>" title="<%= Album.model_name.human %>"><%= Album.model_name.human %></a>
	</li>
	<li<%= " class=active" if %w(photos).include?(action_name) %>>
		<a href="<%= photos_admin_logs_path %>" title="<%= Photo.model_name.human %>"><%= Photo.model_name.human %></a>
	</li>
</ul>

app/views/admin/logs/index.html.erb
<%- model_class = Log -%>
<%= render "base" %>
<%= render "tabs" %>
<table class="table logs">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:message) %></th>
    </tr>
  </thead>
  <tbody>
    <% @logs.each do |log| %>
      <tr>
        <td><%= "#{log.id}#" %></td>
        <td><%= log_tag(log, :model_tag => %w(index).include?(action_name) ? true : false, :popover => true) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="table-footer clearfix">
  <div class="paginates-info"><%= page_entries_info @logs %></div>
  <%= paginate @logs, :theme => "admin" %>
</div>